### PR TITLE
Swift 5 layout

### PR DESCRIPTION
**Pull request by yaroslav-zhurakovskiy**
I reworked the project. I split it into two libraries (one or iOS and one for WatchKit) and two example projects. As for iOS it does not require any resources, but for WatchKit the user will need to add EightBallController.storyboard and EightBallController.xcassets. After that he can use  EightBallController from his WatchKit application, see the example. I am not sure about the names of the libraries. I just picked EightBalliOS and EightBallWatchKit.

### CODE REVIEW

**Comment by fulldecent** [comment]
This project is not a library. It is an end-user product.

People will not be incorporating these items into their own application.

**Comment by fulldecent** [comment]
The scope for this issue is just to update the code to Swift 5 and make any immediate changes that the latest version of Xcode requires.

**Comment by yaroslav-zhurakovskiy** [comment]
So, no Swift 5 layout. Ok....

**Comment by fulldecent** [comment]
This PR makes unwanted changes and is not doing what is requested in the related issue.

The 8 Ball project is an iOS app and a WatchKit app sold on the App Store.

What the issue wants to achieve is to simply update the code to Swift 5.

But actually this PR treats the project like a reusable Swift module, which it is not.

**Comment by fulldecent** [comment]
This PR is superseded by #4

**Pull request closed without merging**
